/*
 * keyboard_conf.h
 *
 *  Created on: Oct 29, 2023
 *      Author: xq123
 */

#ifndef KEYBOARD_CONF_H_
#define KEYBOARD_CONF_H_

//#define EXTENDED_SAMPLING

#define STATIC_RECORD

#define ENABLE_ANALOG_HISTORY

#define ENABLE_KPS

#define ENABLE_KPS_HISTORY

#define ENABLE_BIT_STREAM

#define ENABLE_COUNTER
//#define PAUSE_TIM_WHEN_CALCULATING

#define DEFAULT_ADVANCED_KEY_MODE KEY_ANALOG_RAPID_MODE
//#define DEFAULT_ADVANCED_KEY_MODE KEY_ANALOG_NORMAL_MODE

#define DEFAULT_TRIGGER_DISTANCE 0.08

#define DEFAULT_RELEASE_DISTANCE 0.08

#define DEFAULT_UPPER_DEADZONE 0.04

#define DEFAULT_LOWER_DEADZONE 0.12

#define DEFAULT_SCHMITT_PARAMETER 0.01

#define PULSE 1000
#define PULSE_LEN_MS 40

#endif /* KEYBOARD_CONF_H_ */
